# -*- coding: utf-8 -*-
"""DA_Assignment_3_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wokvyGwV49q9FoIq5tdgSw9-kSotgLnz

## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**
"""

print(7**4)

"""** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **
"""

from posixpath import split
s="Hi there Sam"
x=split(s)
print(x)



"""** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742
print('The diameter of {} is {} kilometers.'.format(planet,diameter))



"""** Given this nested list, use indexing to grab the word "hello" **"""

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2])

"""** Given this nest dictionary grab the word "hello". Be prepared, this will be annoying/tricky **"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

"""** What is the main difference between a tuple and a list? **"""



"""Tuples are immutable.
Lists consume more memory. 
Tuple iterations are faster

** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**
"""

def domainGet(email):
  print("Your domain is: " + email.split('@')[-1])
email = input("Please enter your email: ")
domainGet(email)

def domainGet(email):
  print("Your domain is: " + email.split('@')[-1])
email = input("Please enter your email: ")
domainGet(email)

def domainGet(email):
  print("Your domain is: " + email.split('@')[-1])
domainGet('google@google.com')

"""** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **"""

def func(animal):
  if 'dog' in animal.lower() :
    print('True')
  else:
    print('False')
func('A dog is in the house')

def func(animal):
  if 'dog' in animal.lower() :
    print('True')
  else:
    print('False')
s = input()
func(s)

"""** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **"""

x='I have a dog  who likes the dog next door.' 
def cntno(st) :
  count=0
  for txt in st.lower().split():
    if txt == 'dog' or txt == 'dogs':
      count = count + 1
  print(count)
cntno(x)



"""### Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **
"""

def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
caught_speeding(81,False)

def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
caught_speeding(70,True)

"""Create an employee list with basic salary values(at least 5 values for 5 employees)  and using a for loop retreive each employee salary and calculate total salary expenditure. """

empsal=[50000,51000,60000,65000,66000]
total=0
for x in empsal :
  print(x)
  total=total+x
print(total)

"""Create two dictionaries in Python:

First one to contain fields as Empid,  Empname,  Basicpay

Second dictionary to contain fields as DeptName,  DeptId.

Combine both dictionaries. 
"""

d1={'Empid': 123, 'Empname': 'Sam', 'Basicpay':98000}
d2={'DeptName': 'Marketing','DeptId': '10'}
d1.update(d2)
print(d1)